### ISSUE TITLE
[1.21.1] enableVillagerStructures = false ignored

### ISSUE THREAD

**Issue by SigmaFlame** [Seniorendi/AdvancedPeripherals#722]
### Describe

Hello,

The setting `enableVillagerStructures = false` is ignored.
The setting `villagerStructureWeight = 0` is ignored as well.
Villager Structures are still found inside villages.

AdvancedPeripherals-1.21.1-0.7.49a.jar

### Steps to reproduce

1) Change the setting inside : /config/Advancedperipherals/world.toml
2) Find a village.
3) See the structure is still there, and can be found multiple times.

ComputerCraft is so OP that I have to modify the crafting recipes.
It's not to allow my players to find a lot of advanced computers and turtles inside villages.
At this moment, the only way to prevent them to spawn inside villages is to remove your mod from our modpack.

### Multiplayer?

Yes

### Version

0.7.49a

### Minecraft, Forge and maybe other related mods versions

Minecraft 1.21.1 - Neoforge 21.1.133

### Config

```toml
#Config to adjust world settings
[World]
	#Enable the villager structures for the computer scientist.
	enableVillagerStructures = false
	#Gives the ap documentation to new players.
	givePlayerBookOnJoin = true
	#The weight of the villager structures.
	# Default: 10
	# Range: 0 ~ 16000
	villagerStructureWeight = 0
	#Enable new wandering trader trades.
	enableWanderingTraderTrades = true
```
